--JOINS

CREATE TABLE MYEMPLOYEE(EMPLOYEEID INT, FIRSTNAME VARCHAR(20),LASTNAME VARCHAR(20))
 
 INSERT  INTO MYEMPLOYEE VALUES(1,'Aparna','Vemuganti')
 INSERT  INTO MYEMPLOYEE VALUES(2,'Adithi','Rudraram')
 INSERT  INTO MYEMPLOYEE VALUES(3,'Deepa','Meher')

 SELECT * FROM MYEMPLOYEE




 create table  MYSALARY(EMPLOYEEID INT, SALARY FLOAT)
 INSERT INTO MYSALARY VALUES (1,10000)
 INSERT INTO MYSALARY VALUES (2,8000)
 INSERT INTO MYSALARY VALUES (3,6000)

 ---LEFT OUTERJOIN 
 CREATE TABLE MYPHONE(EMPLOYEEID INT,PHONENUMBER INT)

 INSERT INTO MYPHONE VALUES (1, 1211123342)
 INSERT INTO MYPHONE VALUES (2, 1111111111)

 SELECT * FROM MYEMPLOYEE
 SELECT * FROM  MYPHONE

 SELECT A.FIRSTNAME,A.LASTNAME,B.PHONENUMBER FROM MYEMPLOYEE A LEFT JOIN MYPHONE B
 ON A.EMPLOYEEID = B.EMPLOYEEID


 ---RIGHT JOINS
 CREATE TABLE MYPARKING  (EMPLOYEEID INT,PARKINGSPOT VARCHAR(20))

 INSERT INTO MYPARKING  VALUES (1,'a1')
 INSERT INTO MYPARKING VALUES (2,'a2')

 SELECT * FROM MYEMPLOYEE
 SELECT *FROM MYPARKING

 SELECT  A.PARKINGSPOT,B.FIRSTNAME,B.LASTNAME FROM MYPARKING A RIGHT JOIN MYEMPLOYEE B ON A.EMPLOYEEID=B.EMPLOYEEID



 SELECT * FROM MYEMPLOYEE
 SELECT * FROM MYSALARY


 SELECT  A.FIRSTNAME,A.LASTNAME , B.SALARY
 FROM MYEMPLOYEE A INNER JOIN MYSALARY B ON A.EMPLOYEEID= B.EMPLOYEEID

 ---FULL OUTERJOIN
 CREATE TABLE MYCUSTOMER (CUSTOMERID INT, CUSTOMERNAME VARCHAR(20))

 INSERT INTO MYCUSTOMER VALUES(1,'Aparna')
 INSERT INTO MYCUSTOMER VALUES(2,'Deepa')


 CREATE TABLE MYORDER(ORDERNUMBER INT,ORDERNAME VARCHAR(20), CUSTOMERID INT)

 INSERT INTO MYORDER VALUES(1,'SOMEORDER1',1)
 INSERT INTO MYORDER VALUES(2,'SOMEORDER2',2)
 INSERT INTO MYORDER VALUES(3,'SOMEORDER3',3)
 INSERT INTO MYORDER VALUES(4,'SOMEORDER4',4)

 SELECT  * FROM MYCUSTOMER
 SELECT * FROM MYORDER

 SELECT A.CUSTOMERID ,A.CUSTOMERNAME, B.ORDERNUMBER, B.ORDERNAME 
 FROM  MYCUSTOMER A FULL OUTER JOIN MYORDER B
 ON A.CUSTOMERID = B.CUSTOMERID

 ---CROSS JOIN 


 SELECT * FROM MYCUSTOMER  CROSS JOIN MYSALARY
  --SELECT * FROM MYCUSTOMER  CROSS JOIN MYSALARY
  SELECT * FROM MYCUSTOMER,MYSALARY


  SELECT GETDATE()
   SELECT GETDATE() - 2

   ---DATEPART
SELECT DATEPART(yyyy, GETDATE()) AS YEARNUMBER

SELECT DATEPART(mm,GETDATE())

SELECT DATEPART(dd,GETDATE())

---DATEADD


SELECT DATEADD(day, 4, GETDATE())
SELECT DATEADD(day, 4, '6/1/2023')

SELECT DATEADD(month, 4, GETDATE())

SELECT DATEADD(year, 4, GETDATE())

--
SELECT TOP 10 * FROM [Production].[WorkOrder]

SELECT workOrderID,ProductID,StartDate,EndDate,DATEDIFF(day,StartDate, EndDate)
FROM [Production].[WorkOrder]

SELECT DATEADD(dd, -(DATEPART(day, GETDATE()) - 1), GETDATE())

--MYSALARY
--AGGREGATE FUNCTIONS
SELECT * FROM MYSALARY

SELECT AVG(SALARY) FROM MYSALARY

SELECT COUNT(SALARY) FROM MYSALARY

SELECT COUNT(*) FROM MYSALARY

SELECT * FROM MYSALARY

SELECT SUM(SALARY) FROM MYSALARY

SELECT MIN(SALARY) FROM MYSALARY

SELECT MAX (SALARY) FROM MYSALARY

---MYORDER
SLECT * FROM MYORDER

--CONCAT
PRINT CONCAT('String 1' , '   String 2')

SELECT ORDERNUMBER ,ORDERNAME ,CONCAT(ORDERNAME, ' ',ORDERNAME) AS CONCATENATEDTEXT
FROM MYORDER


SELECT ORDERNUMBER ,ORDERNAME ,CONCAT(ORDERNAME, ' ',RAND()) AS CONCATENATEDTEXT
FROM MYORDER

 --LEFT
SELECT ORDERNUMBER,ORDERNAME, LEFT(ORDERNAME , 5)FROM MYORDER

---RIGHT
SELECT ORDERNUMBER,ORDERNAME, RIGHT(ORDERNAME , 5)FROM MYORDER

--SUBSTRING
SELECT ORDERNUMBER , ORDERNAME,SUBSTRING(ORDERNAME, 2 ,5)FROM MYORDER

--LOWERCASE
SELECT ORDERNUMBER, ORDERNAME,LOWER(ORDERNAME) FROM MYORDER

--UPPERCASE
SELECT ORDERNUMBER,ORDERNAME,UPPER(ORDERNAME)FROM MYORDER

--LENGTH
SELECT ORDERNUMBER,ORDERNAME,LEN(ORDERNAME)FROM MYORDER
SELECT ORDERNUMBER,ORDERNAME,CONCAT(UPPER(LEFT(ORDERNAME,1)),LOWER(SUBSTRING(ORDERNAME, 2, LEN(ORDERNAME)))) FROM MYORDER

---TRIM
SELECT '   Mytext   '
SELECT LEN('  Mytext    ')

--LTRIM
SELECT LTRIM('  Mytext  ')


--RTRIM
SELECT RTRIM('  Mytext  ')

SELECT LTRIM(RTRIM('  Mytext    '))

