use [AdventureWorks2012]


SELECT * FROM [HumanResources].[Department]
--SHOW ME ALL THE DEPARTMENT NAMES
SELECT NAME FROM[HumanResources].[Department]

--SHOW ME ALL THE GROUP
SELECT GROUPNAME FROM [HumanResources].[Department]

--SHOW ME ALL THE DISTINCT GROUPNAME
SELECT DISTINCT GROUPNAME FROM[HumanResources].[Department]

--SHOW ME ALL THE DEPARTMENT NAME WHO ARE A PART OF MANUFACTURING
SELECT NAME, GROUPNAME FROM [HumanResources].[Department]WHERE GROUPNAME LIKE 'MANUFACTURING'

---CALCULATED COLUMNS.

--GIVE ME ALL THE EMPLOYEES FROM THE EMPLOYEE TABLE
SELECT * FROM[HumanResources].[Employee]

--GIVE ME A LIST OF ALL EMPLOYEE WHO HAVE A ORGANIZATION LEVEL-2
SELECT *FROM[HumanResources].[Employee] WHERE ORGANIZATIONLEVEL = 2

--GIVE ME A LIST OF ALL EMPLOYEES WHO HAVE ORGANIZATION LEVEL = 2 OR 3
SELECT * FROM[HumanResources].[Employee] WHERE ORGANIZATIONLEVEL IN (2,3)

--GIVE ME A LIST OF EMPLOYEES WHO HAVE  A TITLE AS FACILITIES MANAGER
SELECT * FROM[HumanResources].[Employee] WHERE JOBTITLE LIKE  'Facilities Manager'

--GIVE ME ALL THE EPLOYEES WHO HAVE A WORD MANAGER IN THEIR TITLE
SELECT *FROM [HumanResources].[Employee] WHERE JOBTITLE LIKE '%Manager'
SELECT *FROM [HumanResources].[Employee] WHERE JOBTITLE LIKE '%Control%'

--GIVE ME ALL EMPLOYEE WHO ARE BORN AFTER Jaan 1,1980
SELECT *FROM [HumanResources].[Employee] WHERE Birthdate> '1/1/1980'


--GIVE ME ALL EMPLOYEES WHO ARE BORN BETWEEN Jan1,1970 and Jan1,1980
SELECT * FROM [HumanResources].[Employee] WHERE BIRTHDATE > '1/1/1970' AND BirthDate < '1/1/1980'

SELECT * FROM [HumanResources].[Employee] WHERE BIRTHDATE BETWEEN  '1/1/1970' AND  '1/1/1980'